# Linear Regression

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 
%matplotlib inline

In [2]:
cmp = pd.read_csv("C:\\Users\\KIRTI PRATIHAR\\JUPYTER IDIOT\\Machine Learning Algorithm\\1000_Companies.csv")
x= cmp.iloc[:,:-1].values
y=cmp.iloc[:,4].values
cmp.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

## Data Visualisation
## Building the correlation Matrix

In [3]:

numeric_data = cmp.select_dtypes(include=['float64', 'int64'])
#sns.heatmap(cmp.corr())-this will give error as there are non numeric data present
corr_matrix = numeric_data.corr()
sns.heatmap(corr_matrix, annot=True)
corr_matrix = numeric_data.corr()
#sns.heatmap(corr_matrix, annot=True, cmap='coolwarm') cmap- chooses the tone

## Encoding categorical data

In [4]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
x[:,3]=labelencoder.fit_transform(x[:,3])#this will covert state like new york into numbers

# Use OneHotEncoder with ColumnTransformer for one-hot encoding
ct = ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(), [3])],  # Apply OneHotEncoder to column index 3
    remainder='passthrough'  # Keep other columns unchanged
)

# Transform and convert to NumPy array
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 ...
 [1.0 0.0 0.0 100275.47 241926.31 227142.82]
 [1.0 0.0 0.0 128456.23 321652.14 281692.32]
 [0.0 0.0 1.0 161181.72 270939.86 295442.17]]


## Avoid Dummy Variable

In [5]:
x=x[:,1:]

## Splitting the data into training set and testing set

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

## Fitting Multiple Linear Regression to the Training set

In [7]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

## Predicting the test set results

In [8]:
y_pred =reg.predict(x_test)
y_pred

array([ 89790.61532916,  88427.07187361,  94894.67836972, 175680.8672561 ,
        83411.73042089, 110571.90200074, 132145.2293644 ,  91473.37719687,
       164597.05380606,  53222.82667401,  66950.1905099 , 150566.43987004,
       126915.20858596,  59337.8597105 , 177513.91053061,  75316.28143051,
       118248.14406603, 164574.40699901, 170937.2898107 , 182069.11645084,
       118845.03252689,  85669.95112229, 180992.59396143,  84145.08220145,
       105005.83769214, 101233.56772747,  53831.07669092,  56881.41475225,
        68896.39346905, 210040.00765883, 120778.72270894, 111724.87157654,
       101487.90541518, 137959.02649624,  63969.95996744, 108857.91214126,
       186014.72531987, 171442.64130747, 174644.26529204, 117671.49128195,
        96731.37857433, 165452.25779409, 107724.34331255,  50194.54176914,
       116513.89532179,  58632.48986821, 158416.46827609,  78541.4852161 ,
       159727.66671743, 131137.87699644, 184880.70924516, 174609.08266879,
        93745.66352059,  

## Calculate the cofficients 

In [9]:
print(reg.coef_)

[-8.80536598e+02 -6.98169073e+02  5.25845857e-01  8.44390881e-01
  1.07574255e-01]


## Calculate the intersept

In [10]:

print(reg.intercept_)

-51035.22972402157


## calculate the R squared value

In [11]:

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9112695892268807